def get_lot_names (): 
    return {
        1: "Productes químics i reactius", 
        2: "Productes i accessoris per a Biologia, Geologia i Medicina", 
        3: "Productes i accessoris per a Química i Mediambient",
        4: "Material General de laboratori",
        5: "Instrumentació general i auxiliar de laboratori", 
        6: "Equips de mesura",
        7: "Equips i Material de Seguretat i Protecció"
    }

def get_csuc_names(): 
    return {
        101:	"Àcids i Bases",
        102:	"Compostos Inorgànics",
        103:	"Compostos Orgànics",
        104:	"Dissolvents",
        105:	"Kits de química i altres reactius", 
        106:	"Reactius tincions i colorants",
        107:	"Antibiòtics, farmacs i productes naturals",
        108:	"Reactius de síntesi peptídica",
        109:	"Enzims",
        110:	"Altres productes químics i reactius",
        201:	"Reactius, material fungible i accessoris per a Biologia Molecular",
        202:	"Reactius, material fungible i accessoris per a Cultiu Cel·lular",
        203:	"Reactius, material fungible i accessoris per a Microbiologia",
        204:	"Reactius, material fungible i accessoris per a Disecció i Anatomia",
        205:	"Reactius, material fungible i instrumetal per a Cirugia",
        206:	"Reactius, material fungible i accessoris per a Estabularis",
        207:	"Reactius, material fungible i accessoris pel Tallat i Polit de mostres",
        208:	"Reactius, material fungible i accessoris per a Geologia" ,
        209:	"Reactius, material fungible i accessoris per a Microscòpia Òptica",
        210:	"Reactius, material fungible i accessoris per a Microscòpia Electrònica",
        211:	"Altres reactius, material fungible i accessoris específics",
        212:	"Kits de Laboratori" ,
        213:	"Cèl.lules",
        301:	"Reactius, material fungible i accessoris de Cromatografia" ,
        302:	"Reactius, material fungible i accessoris per a Filtració",
        303:	"Altres reactius, material fungible i accessoris específics",
        401:	"Material metàl·lic de Laboratori" ,
        402:	"Material de plàstic de Laboratori" ,
        403:	"Material de vidre/borosilicat de Laboratori",
        404:	"Material de porcellana / àgata / ceràmic / alúmina / polimèric, ..., de Laboratori",
        405:	"Material de paper de Laboratori",
        406:	"Altre material fungible de Laboratori",
        501:	"Micropipetes i Micropipetes automàtiques",
        502:	"Equips d’esterilització",
        503:	"Equips tèrmics",
        504:	"Equips d'evaporació",
        505:	"Equips de purificació d'aigua",
        506:	"Banys d'ultrasons",
        507:	"Equips d’agitació",
        508:	"Molins , morters i sedassos",
        509:	"Talladores i polidores",
        510:	"Equips de pressió",
        511:	"Bombes de trasvàs",
        512:	"Bombes de buit",
        513:	"Equips de filtració",
        514:	"Equips d'extracció en fase sòlida (SPE)",
        515:	"Liofilitzadors",
        516:	"Làmpades UV",
        517:	"Transil.luminadors",
        518:	"Equips de centrifugació (centrífugues i microcentrífugues)",
        519:	"Equips de rentat de material de Laboratori",
        520:	"Equips de rentat de roba de Laboratori",
        521:	"Dosificadors",
        522:	"Fonts d'il.luminació",
        523:	"Petit material electrònic",
        524:	"Accessoris per a equips de Laboratori",
        525:	"Altres instruments, d'us general de Laboratori",
        601:	"Balances, granetaris i bàscules",
        602:	"Peses de calibració",
        603:	"Termòmetres i, psicròmetres",
        604:	"Higròmetres",
        605:	"Baròmetres",
        606:	"Manòmetres",
        607:	"Anemòmetres",
        608:	"Voltímetres i amperímetres",
        609:	"Polímetres",
        610:	"Viscosímetres",
        611:	"Rellotges i cronòmetres",
        612:	"Comptadors",
        613:	"Refractòmetres",
        614:	"Fotòmetres",
        615:	"Luxòmetres",
        616:	"pH metres",
        617:	"Mesuradors de DBOxigen",
        618:	"Escalímetres, galgues, peus de rei i palmers",
        619:	"Cabalímetres",
        620:	"Altres aparells de mesura",
        701:	"Bates i davantals",
        702:	"Roba laboral",
        703:	"Roba de quiròfan",
        704:	"Material de protecció personal d'un sol ús",
        705:	"Protectors auditius",
        706:	"Cascs",
        707:	"Casquets",
        708:	"Guants de protecció",
        709:	"Ulleres de protecció",
        710:	"Mascaretes i filtres",
        711:	"Pantalles facials",
        712:	"Calçat de treball i de seguretat",
        713:	"Altres Equips de Protecció Individual (EPI's)",
        714:	"Kits de protecció personal per a estudiants",
        715:	"Mantes ignífugues",
        716:	"Arnesos i cinturons de seguretat",
        717:	"Dispensadors de material de seguretat",
        718:	"Filtres per vitrines de gasos i cabines de bioseguretat",
        719:	"Material i productes per contenir vessaments",
        720:	"Material i productes per neutralitzar vessaments",
        721:	"Material i envasos per la recollida i gestió de residus i vessaments",
        722:	"Bombes de transvasament i de recollida",
        723:	"Cubetes de retenció i dispositius pel transvàs de productes químics",
        724:	"Farmacioles fixes i portàtils",
        725:	"Material per a farmacioles",
        726:	"Material de primers auxilis, rentaulls portàtils",
        727:	"Xeringues i dispositius d’extracció de sang amb seguretat",
        728:	"Caixes pel transport de mostres biològiques amb seguretat",
        729:	"Elements auxiliars de transport",
        730:	"Productes de neteja i manteniment (EPIS)",
        731:	"Material de salvament marítim",
        732:	"Senyalització de seguretat",
        733:	"Etiquetatge de seguretat",
        734:	"Centraletes d'alarmes",
        735:	"Detectors de fum, de gas, etc  i  detectors portàtils de gasos.",
        736:	"Avisadors acústics",
        737:	"Polsadors d'emergència",
        738:	"Sistemes d'extracció antideflagrants",
        739:	"Sistemes d'il.luminació antideflagrants",
        740:	"Rentaulls",
        741:	"Dutxes d'emergència",
        742:	"Armaris de seguretat, kits d'extracció i filtres",
        743:	"Cadires de Laboratori",
        744:	"Elements auxiliars ergonomia",
        745:	"Extintors",
        746:	"Boques d'incendies equipades (BIE)",
        747:	"Mànegues contraincendis",
        748:	"Altres  equips i material de seguretat i protecció"
    }